import { sendAutoNewsletterNotification } from "~/server/email/transactional/adminNotificationEmail";
import { awsSesProvider } from "~/server/email/providers/awsSes";
import { TopicFactory, IssueFactory } from "~/test/factories";

vi.mock("~/server/email/providers/awsSes", () => ({
  awsSesProvider: {
    sendEmail: vi.fn(),
  },
}));

vi.mock("~/env", () => ({
  env: {
    ADMIN_EMAIL: "adminemail@gmail.com",
    AWS_SES_FROM_EMAIL: "noreply@test.com",
    AWS_SES_TRANSACTIONAL_CONFIG_SET: "test-config-set",
  },
}));

const mockedAwsSesProvider = vi.mocked(awsSesProvider);

describe("sendAutoNewsletterNotification", () => {
  const mockTopic = TopicFactory.createTopic({
    id: 1,
    title: "Load Balancing",
  });

  const mockIssue = IssueFactory.createIssue({
    id: 10,
    topicId: 1,
    status: "approved",
  });

  const defaultSuccessResult = {
    status: "sent" as const,
    messageId: "test-message-id",
    userId: "system",
  };

  beforeEach(() => {
    vi.clearAllMocks();
    vi.spyOn(console, "log").mockImplementation(() => {});
    vi.spyOn(console, "error").mockImplementation(() => {});
    mockedAwsSesProvider.sendEmail.mockResolvedValue(defaultSuccessResult);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe("when auto-generated and auto-approved", () => {
    it("sends email with auto-generation subject and content", async () => {
      await sendAutoNewsletterNotification({
        topic: mockTopic,
        issue: mockIssue,
        wasAutoGenerated: true,
        wasAutoApproved: true,
        sequenceNumber: 42,
      });

      const callArgs = mockedAwsSesProvider.sendEmail.mock.calls[0]![0];

      expect(callArgs.subject).toBe(
        "🚨 [Daily System Design] Newsletter Auto-Generated & Auto-Approved - Issue #42",
      );
      expect(callArgs.html).toContain("Auto-Generated & Auto-Approved");
      expect(callArgs.html).toContain("generated a new newsletter and");
      expect(callArgs.text).toContain("Auto-Generated & Auto-Approved");
      expect(callArgs.text).toContain("generated a new newsletter and");
    });
  });

  describe("when auto-approved from existing draft", () => {
    it("sends email with existing-draft subject and content", async () => {
      await sendAutoNewsletterNotification({
        topic: mockTopic,
        issue: mockIssue,
        wasAutoGenerated: false,
        wasAutoApproved: true,
        sequenceNumber: 15,
      });

      const callArgs = mockedAwsSesProvider.sendEmail.mock.calls[0]![0];

      expect(callArgs.subject).toBe(
        "🚨 [Daily System Design] Newsletter Auto-Approved (from existing draft) - Issue #15",
      );
      expect(callArgs.html).toContain("Auto-Approved (from existing draft)");
      expect(callArgs.html).not.toContain("generated a new newsletter and");
      expect(callArgs.text).toContain("Auto-Approved (from existing draft)");
      expect(callArgs.text).not.toContain("generated a new newsletter and");
    });
  });

  describe("email configuration", () => {
    it("sends with correct recipient, sender, config set, tags, and userId", async () => {
      await sendAutoNewsletterNotification({
        topic: mockTopic,
        issue: mockIssue,
        wasAutoGenerated: true,
        wasAutoApproved: true,
        sequenceNumber: 1,
      });

      expect(mockedAwsSesProvider.sendEmail).toHaveBeenCalledWith(
        expect.objectContaining({
          to: "adminemail@gmail.com",
          from: "noreply@test.com",
          deliveryConfiguration: "test-config-set",
          tags: [{ name: "email_type", value: "admin_notification" }],
          userId: "system",
        }),
      );
    });
  });

  describe("logging", () => {
    it("logs success with MessageId on successful send", async () => {
      mockedAwsSesProvider.sendEmail.mockResolvedValue({
        status: "sent",
        messageId: "success-msg-id-999",
        userId: "system",
      });

      await sendAutoNewsletterNotification({
        topic: mockTopic,
        issue: mockIssue,
        wasAutoGenerated: true,
        wasAutoApproved: true,
        sequenceNumber: 1,
      });

      expect(console.log).toHaveBeenCalledWith(
        expect.stringContaining("[AutoNewsletter] Admin notification sent"),
      );
      expect(console.log).toHaveBeenCalledWith(
        expect.stringContaining("success-msg-id-999"),
      );
    });

    it("logs error when email returns failed status", async () => {
      mockedAwsSesProvider.sendEmail.mockResolvedValue({
        status: "failed",
        error: "SES quota exceeded",
        userId: "system",
      });

      await sendAutoNewsletterNotification({
        topic: mockTopic,
        issue: mockIssue,
        wasAutoGenerated: true,
        wasAutoApproved: true,
        sequenceNumber: 1,
      });

      expect(console.error).toHaveBeenCalledWith(
        expect.stringContaining(
          "[AutoNewsletter] Failed to send admin notification",
        ),
      );
      expect(console.error).toHaveBeenCalledWith(
        expect.stringContaining("SES quota exceeded"),
      );
    });
  });

  describe("error handling", () => {
    it("catches and logs errors without throwing", async () => {
      mockedAwsSesProvider.sendEmail.mockRejectedValue(
        new Error("Network connection failed"),
      );

      await expect(
        sendAutoNewsletterNotification({
          topic: mockTopic,
          issue: mockIssue,
          wasAutoGenerated: true,
          wasAutoApproved: true,
          sequenceNumber: 1,
        }),
      ).resolves.toBeUndefined();

      expect(console.error).toHaveBeenCalledWith(
        expect.stringContaining(
          "[AutoNewsletter] Error sending admin notification",
        ),
        "Network connection failed",
      );
    });

    it("handles non-Error exceptions gracefully", async () => {
      mockedAwsSesProvider.sendEmail.mockRejectedValue("String error");

      await sendAutoNewsletterNotification({
        topic: mockTopic,
        issue: mockIssue,
        wasAutoGenerated: true,
        wasAutoApproved: true,
        sequenceNumber: 1,
      });

      expect(console.error).toHaveBeenCalledWith(
        expect.stringContaining(
          "[AutoNewsletter] Error sending admin notification",
        ),
        "String error",
      );
    });
  });
});
