import { awsSesProvider } from "../providers/awsSes";
import { env } from "~/env";
import type { Topic } from "~/server/db/schema/topics";
import type { Issue } from "~/server/db/schema/issues";
export interface AutoNewsletterNotificationParams {
  topic: Topic;
  issue: Issue;
  wasAutoGenerated: boolean;
  wasAutoApproved: boolean;
  sequenceNumber: number;
}

/**
 * Sends a notification email to the admin when a newsletter is auto-generated or auto-approved.
 */
export async function sendAutoNewsletterNotification(
  params: AutoNewsletterNotificationParams,
): Promise<void> {
  const { topic, issue, wasAutoGenerated, sequenceNumber } = params;

  const actionType = wasAutoGenerated
    ? "Auto-Generated & Auto-Approved"
    : "Auto-Approved (from existing draft)";

  const timestamp = new Date().toLocaleString("en-US", {
    timeZone: "America/Los_Angeles",
    dateStyle: "full",
    timeStyle: "long",
  });

  const subject = `🚨 [Daily System Design] Newsletter ${actionType} - Issue #${sequenceNumber}`;

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #f59e0b; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .content { background: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px; }
    .info-row { margin: 10px 0; }
    .label { font-weight: 600; color: #6b7280; }
    .value { color: #111827; }
    .alert-box { background: #fef3c7; border: 1px solid #f59e0b; padding: 15px; border-radius: 6px; margin: 15px 0; }
    .footer { margin-top: 20px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }
  </style>
</head>
<body>
  <div class="header">
    <h1 style="margin: 0; font-size: 20px;">Newsletter ${actionType}</h1>
  </div>
  <div class="content">
    <div class="alert-box">
      <strong>Automatic Action Taken:</strong> The cron job did not find an approved newsletter for today's topic, so it ${wasAutoGenerated ? "generated a new newsletter and" : ""} auto-approved it for sending.
    </div>
    
    <div class="info-row">
      <span class="label">Issue Number:</span>
      <span class="value">#${sequenceNumber}</span>
    </div>
    
    <div class="info-row">
      <span class="label">Topic Title:</span>
      <span class="value">${topic.title}</span>
    </div>
    
    <div class="info-row">
      <span class="label">Issue ID:</span>
      <span class="value">${issue.id}</span>
    </div>
    
    <div class="info-row">
      <span class="label">Topic ID:</span>
      <span class="value">${topic.id}</span>
    </div>
    
    <div class="info-row">
      <span class="label">Action Taken:</span>
      <span class="value">${actionType}</span>
    </div>
    
    <div class="info-row">
      <span class="label">Timestamp:</span>
      <span class="value">${timestamp}</span>
    </div>
    
    <div class="footer">
      <p>This notification was sent because the daily newsletter cron job automatically ${wasAutoGenerated ? "generated and " : ""}approved a newsletter that was not pre-approved.</p>
      <p>If you want to prevent this in the future, make sure to review and approve newsletters before the scheduled send time.</p>
    </div>
  </div>
</body>
</html>
`;

  const textContent = `
Newsletter ${actionType}

The cron job did not find an approved newsletter for today's topic, so it ${wasAutoGenerated ? "generated a new newsletter and" : ""} auto-approved it for sending.

Issue Number: #${sequenceNumber}
Topic Title: ${topic.title}
Issue ID: ${issue.id}
Topic ID: ${topic.id}
Action Taken: ${actionType}
Timestamp: ${timestamp}

---
This notification was sent because the daily newsletter cron job automatically ${wasAutoGenerated ? "generated and " : ""}approved a newsletter that was not pre-approved.

If you want to prevent this in the future, make sure to review and approve newsletters before the scheduled send time.
`;

  try {
    const result = await awsSesProvider.sendEmail({
      to: env.ADMIN_EMAIL,
      from: env.AWS_SES_FROM_EMAIL,
      subject,
      html: htmlContent,
      text: textContent,
      userId: "system",
      deliveryConfiguration: env.AWS_SES_TRANSACTIONAL_CONFIG_SET,
      tags: [{ name: "email_type", value: "admin_notification" }],
    });

    if (result.status === "sent") {
      console.log(
        `[AutoNewsletter] Admin notification sent to ${env.ADMIN_EMAIL} (MessageId: ${result.messageId})`,
      );
    } else {
      console.error(
        `[AutoNewsletter] Failed to send admin notification: ${result.error}`,
      );
    }
  } catch (error) {
    console.error(
      `[AutoNewsletter] Error sending admin notification:`,
      error instanceof Error ? error.message : error,
    );
  }
}
